/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulaire;

import static dao.DatabaseService.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Utilisateur;

/**
 *
 * @author user
 */
public class DemieFinal extends javax.swing.JFrame {

    /**
     * Creates new form DemieFinal
     */
    public DemieFinal() {
        initComponents();
    }
    public DemieFinal(Utilisateur u,long t) throws SQLException, ClassNotFoundException {
        initComponents();
         this.u1=u;
         this.t1=t;
        con = getConnection();
        if(CompterMatchDemie(con,t1)==0){
                TirageDemie(con, t1);    
                 fetch();
        }else{
             fetch();
        }
        
//        fetch();
        
        }
 Utilisateur u1;
    long t1;
     ResultSet rs;
    Connection con;
    PreparedStatement pst;
    
    public static int CompterMatchDemie(Connection con, long t1) throws SQLException {
               PreparedStatement pst;
               ResultSet rs;           
    int total = 0;
    long id_tournois=t1; 
    pst = con.prepareStatement("SELECT COUNT(*) AS total_final FROM final WHERE  id_tournois = ?");
//    pst.setLong(1, id); 
    pst.setLong(1, id_tournois); 
    rs = pst.executeQuery();
    if (rs.next()) {
        total = rs.getInt("total_final");
    }
    return total;
}
     private void fetch () {
         try {
            int q;
            long id=t1;
            pst = con.prepareStatement("SELECT * FROM final WHERE id_tournois = ?");
            pst.setLong(1,id);
            rs = pst.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            q=rss.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)tableaumatchmaking.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for (int a=1 ; a<=q ;a++) {
                   v2.add(rs.getString("id_joueur1"));
                   v2.add(rs.getString("id_joueur2"));
                   v2.add(rs.getString("numero_match"));
                }
                df.addRow(v2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ListeJoueurs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public static void TirageDemie(Connection con, long idTournois) throws SQLException {
       
//        String sqlSelect = "SELECT id_gagnant FROM scores WHERE id_tournois = ?";
//        PreparedStatement pstSelect = con.prepareStatement(sqlSelect);

        PreparedStatement pst = con.prepareStatement("SELECT id_gagnant FROM scores WHERE id_tournois = ?");
        pst.setLong(1, idTournois);
        ResultSet rs = pst.executeQuery();
        

        List<Long> joueurs = new ArrayList<>();
        while (rs.next()) {
            joueurs.add(rs.getLong("id_gagnant"));
        }
        rs.close();
        pst.close();
        if (joueurs.size() < 2) {
            JOptionPane.showMessageDialog(null, "Pas assez de joueurs pour générer des matchs.");
            return;
        }
       
        Collections.shuffle(joueurs);

        pst = con.prepareStatement("INSERT INTO final (id_joueur1, id_joueur2, id_tournois, numero_match) VALUES (?, ?, ?, ?)");
        
       for (int i = 0; i + 1 < joueurs.size(); i += 2) {
    int matchNum = (i / 2) + 1;
        pst.setLong(1, joueurs.get(i));
        pst.setLong(2, joueurs.get(i + 1));
        pst.setLong(3, idTournois);
        pst.setInt(4, matchNum);
        pst.executeUpdate();
        
}
        pst.close();
        JOptionPane.showMessageDialog(null, "Matchs crees avec succeess.");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableaumatchmaking = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        score_p3 = new javax.swing.JTextField();
        apply_match2 = new javax.swing.JButton();
        score_p4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        score_p5 = new javax.swing.JTextField();
        apply_match3 = new javax.swing.JButton();
        score_p6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableaumatchmaking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Player1       vs", "Player2", "Match"
            }
        ));
        tableaumatchmaking.setFocusable(false);
        tableaumatchmaking.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tableaumatchmaking.setShowHorizontalLines(true);
        tableaumatchmaking.setShowVerticalLines(true);
        tableaumatchmaking.getTableHeader().setResizingAllowed(false);
        jScrollPane2.setViewportView(tableaumatchmaking);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEMI-FINALE");

        jLabel4.setText("Match 1 selectionner gagnant:");

        jLabel5.setText("SCORE:");

        score_p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score_p3ActionPerformed(evt);
            }
        });

        apply_match2.setText("Apply");
        apply_match2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_match2ActionPerformed(evt);
            }
        });

        score_p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score_p4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score_p3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(score_p4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(apply_match2)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(score_p3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apply_match2)
                    .addComponent(score_p4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel10.setText("Match 2 selectionner gagnant:");

        jLabel11.setText("SCORE:");

        score_p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score_p5ActionPerformed(evt);
            }
        });

        apply_match3.setText("Apply");
        apply_match3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_match3ActionPerformed(evt);
            }
        });

        score_p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score_p6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(24, 24, 24)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score_p5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(score_p6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(apply_match3)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(score_p5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apply_match3)
                    .addComponent(score_p6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel9.setText("P1           P2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 184, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void score_p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score_p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_score_p3ActionPerformed

    private void apply_match2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_match2ActionPerformed
        try {
            long gagnant;
            String score_1 = score_p1.getText().trim();
            String score_2 = score_p2.getText().trim();
            if (!score_1.matches("\\d+") || !score_2.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Veuillez saisir uniquement des chiffres pour les scores.");
                return;
            }

            long score_11 = Long.parseLong(score_1);
            long score_22 = Long.parseLong(score_2);

            if (score_11 < 0 || score_22<0) {
                JOptionPane.showMessageDialog(this, "Pas de negatif.");
                return;
            }

            if (score_11 == score_22) {
                JOptionPane.showMessageDialog(this, "Pas de match nul.");
                return;
            }

            long id_match = 1;
            long id_tournois=t1;

            pst = con.prepareStatement("SELECT id_joueur1, id_joueur2 FROM matchs WHERE numero_match = 1 AND id_tournois = ?");
            pst.setLong(1, id_tournois);
            rs = pst.executeQuery();

            if (rs.next()) {
                long id_j1 = rs.getLong("id_joueur1");
                long id_j2 = rs.getLong("id_joueur2");
 
                if (score_11 > score_22) {
                    gagnant = id_j1;
                } else {
                    gagnant = id_j2;
                }

                JOptionPane.showMessageDialog(this, "Le gagnant est le joueur avec l'ID : " + gagnant);
                PreparedStatement pstInsert = con.prepareStatement(
                    "INSERT INTO scores (id_match, id_gagnant, score_joueur1, score_joueur2, id_tournois) VALUES (?, ?, ?, ?, ?)"
                );
                pstInsert.setLong(1, id_match);
                pstInsert.setLong(2, gagnant);
                pstInsert.setLong(3, score_11);
                pstInsert.setLong(4, score_22);
                pstInsert.setLong(5, id_tournois);
                pstInsert.executeUpdate();
                pstInsert.close();

                JOptionPane.showMessageDialog(this, "Score enregistré avec succès.");
                apply_match1.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Aucun match trouvé.");
            }

            rs.close();
            pst.close();

        } catch (SQLException ex) {
            Logger.getLogger(ResultatMatch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_apply_match2ActionPerformed

    private void score_p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score_p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_score_p4ActionPerformed

    private void score_p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score_p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_score_p5ActionPerformed

    private void apply_match3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_match3ActionPerformed
        // TODO add your handling code here:
        try {
            long gagnant;
            String score_3 = score_p3.getText().trim();
            String score_4 = score_p4.getText().trim();
            if (!score_3.matches("\\d+") || !score_4.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Veuillez saisir uniquement des chiffres pour les scores.");
                return;
            }

            long score_33 = Long.parseLong(score_3);
            long score_44 = Long.parseLong(score_4);

            if (score_33 < 0 || score_44<0) {
                JOptionPane.showMessageDialog(this, "Pas de negatif.");
                return;
            }

            if (score_33 == score_44) {
                JOptionPane.showMessageDialog(this, "Pas de match nul.");
                return;
            }

            long id_match = 2;
            long id_tournois=t1;

            pst = con.prepareStatement("SELECT id_joueur1, id_joueur2 FROM matchs WHERE numero_match = 2 AND id_tournois=?");
            pst.setLong(1, id_tournois);
            rs = pst.executeQuery();

            if (rs.next()) {
                long id_j3 = rs.getLong("id_joueur1");
                long id_j4 = rs.getLong("id_joueur2");

                if (score_33 > score_44) {
                    gagnant = id_j3;
                } else {
                    gagnant = id_j4;
                }

                JOptionPane.showMessageDialog(this, "Le gagnant est le joueur avec l'ID : " + gagnant);
                PreparedStatement pstInsert = con.prepareStatement("INSERT INTO scores (id_match, id_gagnant, score_joueur1, score_joueur2, id_tournois) VALUES (?, ?, ?, ?, ?)");
                pstInsert.setLong(1, id_match);
                pstInsert.setLong(2, gagnant);
                pstInsert.setLong(3, score_33);
                pstInsert.setLong(4, score_44);
                pstInsert.setLong(5, id_tournois);
                pstInsert.executeUpdate();
                pstInsert.close();

                JOptionPane.showMessageDialog(this, "Score enregistré avec succès.");
                apply_match2.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Aucun match trouvé.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ResultatMatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_apply_match3ActionPerformed

    private void score_p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score_p6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_score_p6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemieFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemieFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemieFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemieFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemieFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apply_match1;
    private javax.swing.JButton apply_match2;
    private javax.swing.JButton apply_match3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField score_p1;
    private javax.swing.JTextField score_p2;
    private javax.swing.JTextField score_p3;
    private javax.swing.JTextField score_p4;
    private javax.swing.JTextField score_p5;
    private javax.swing.JTextField score_p6;
    private javax.swing.JTable tableaumatchmaking;
    // End of variables declaration//GEN-END:variables
}
